repos:
  - repo: https://gitlab.com/flywheel-io/tools/etc/pre-commit-hooks
    rev: a0d59a94e67f8f00032b31ae5c48dbe52d6ce9bb
    hooks:
      - id: flywheel-lint
      - id: docker-update
      - id: docker-test
