repos:
  - repo: https://gitlab.com/flywheel-io/tools/etc/pre-commit-hooks
    rev: 5307acc41a140fe928ce48604a915dbcc3db322c
    hooks:
      - id: flywheel-lint
      - id: docker-update
      - id: docker-test
